In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ -12.481023 ,  168.58885  ,   33.60884  ,    5.5547023,
          67.747375 , -158.17093  ,   22.821909 , -210.45947  ,
          44.96251  ,  -42.757347 ]], dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

326.75977

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 2.2531 - accuracy: 0.7475
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5861 - accuracy: 0.8407
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4870 - accuracy: 0.8668
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4238 - accuracy: 0.8842
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3940 - accuracy: 0.8943


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.2781 - accuracy: 0.9371


[0.27814680337905884, 0.9370999932289124]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 0.0000000e+00, 1.2085104e-22, 3.8713927e-16,
        6.8158251e-29, 1.0561103e-29, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 8.5941075e-16],
       [9.4516955e-19, 3.0695935e-04, 9.9968290e-01, 9.6953354e-06,
        5.7261383e-28, 6.2070132e-10, 3.4076938e-22, 4.4654416e-07,
        1.5777246e-11, 3.0534254e-22],
       [8.3205055e-26, 1.0000000e+00, 1.5157637e-13, 5.6224111e-23,
        4.8198387e-19, 9.2344389e-20, 1.4077196e-10, 1.0913061e-12,
        7.6344514e-11, 3.6499189e-29],
       [9.9995553e-01, 1.5466868e-33, 1.1445585e-07, 2.9184394e-17,
        6.9896666e-22, 4.4399418e-05, 2.1626869e-09, 2.5807453e-10,
        1.2691439e-17, 2.2207201e-12],
       [9.1675251e-25, 4.1254988e-24, 3.2504710e-07, 6.3743227e-13,
        9.9999332e-01, 1.3765551e-09, 2.3935290e-16, 6.6816000e-08,
        3.0649303e-11, 6.2291783e-06]], dtype=float32)>

In [14]:
#epoch num is 5
#When you don't include the x_train, x_test = x_train / 255.0, x_test / 255.0 the accuracy is .9371, init first loss = 326.75977
#when included the accuracy is .9764, init first loss = 2.689857 